APPS = [
    {
        "key": "customer_support_bot",
        "name": "Customer Support Bot",
        "app_type": "customer_facing",
        "latency_budget_ms": 300,
        "risk_tolerance": "low",
        "weight_performance": 0.40,
        "weight_cost": 0.25,
        "weight_responsibility": 0.35,
        "daily_budget_usd": 15.0,
    },
    {
        "key": "internal_copilot",
        "name": "Internal Knowledge Copilot",
        "app_type": "internal",
        "latency_budget_ms": 2000,
        "risk_tolerance": "medium",
        "weight_performance": 0.35,
        "weight_cost": 0.40,
        "weight_responsibility": 0.25,
        "daily_budget_usd": 30.0,
    },
    {
        "key": "decision_support_tool",
        "name": "Underwriting Decision-Support Tool",
        "app_type": "decision_support",
        "latency_budget_ms": 5000,
        "risk_tolerance": "low",
        "weight_performance": 0.30,
        "weight_cost": 0.15,
        "weight_responsibility": 0.55,
        "daily_budget_usd": 40.0,
    },
]
